export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";

export const FETCH_UPCOMING_LAUNCH = "FETCH_UPCOMING_LAUNCH";
export const FETCH_UPCOMING_LAUNCH_REQUEST = "FETCH_UPCOMING_LAUNCH_REQUEST";
export const FETCH_UPCOMING_LAUNCH_SUCCESS = "FETCH_UPCOMING_LAUNCH_SUCCESS";
export const FETCH_UPCOMING_LAUNCH_FAILED = "FETCH_UPCOMING_LAUNCH_FAILED";

export const FETCH_LAUNCHES = "FETCH_LAUNCHES";
export const FETCH_LAUNCHES_REQUEST = "FETCH_LAUNCHES_REQUEST";
export const FETCH_LAUNCHES_SUCCESS = "FETCH_LAUNCHES_SUCCESS";
export const FETCH_LAUNCHES_FAILED = "FETCH_LAUNCHES_FAILED";

export const SET_QUERY_PAGE = "SET_QUERY_PAGE";
export const SET_QUERY_SEARCH = "SET_QUERY_SEARCH";
